export const assets = {
  global: {
    ick_logo: "./basics/Ick-logo.png",
    footerImg: "./basics/trackImg.jpg",
    hindustanMotorsportsLogo: "./basics/hindustan-motorsports.png",
    dotPattern: "/basics/dots-pattern.svg",
    hfkcLogo: "/basics/hfkc.png",
    commingSoon: '/basics/comming-soon.jpg'
  },
  heroSection: {
    backGroundVideo: "./hero/karting-video.mp4",
  },
  seasonSection: {
    tyre: "./season/tyre.png",
    person: "./season/aPerson.png",
    quadBiking: "./season/quad-bike-png.png",
    dirtBiking: "./season/dirt-bikingPng.jpg",
    hfkcLogo: "/season/hfkc.png",
    issSeason: "/season/ISS-series.png",
  },
  aboutSection: {
    smallKart: "./about/smallKart.png",
    NexusMotoSport: "./about/NexusMotoSport.jpg",
    IndianKarting: "./about/IndianKarting.jpg",
  },
  committeeSection: {
    Abhishek: "./committiee/AbhishekKaranjule.jpg",
    Aniket: "./committiee/AniketMind.jpg",
    Azmat: "./committiee/AzmatHussain.jpg",
  },
  socialIcons: {
    dribble: "./socialIcons/dribble.svg",
    linkedIn: "./socialIcons/linkedin.svg",
    facebook: "./socialIcons/facebook.svg",
  },
  gallery: {
    img_1: "https://i.imghippo.com/files/RFGQO1719859085.jpg",
    img_2: "https://i.imghippo.com/files/EIQJF1719859197.jpg",
    img_3: "https://i.imghippo.com/files/g4g511719859219.jpg",
    img_4: "https://i.imghippo.com/files/CQNz81719859244.jpg",
    img_5: "https://i.imghippo.com/files/B43fm1719859425.jpg",
    img_6: "https://i.imghippo.com/files/B43fm1719859425.jpg",
    img_7: "https://i.imghippo.com/files/Pt3Rn1719859677.jpg",
    img_8: "https://i.imghippo.com/files/UtEjJ1719859718.jpg",
    img_9: "https://i.imghippo.com/files/m1gkM1719859744.jpg",
    img_10: "https://i.imghippo.com/files/m1gkM1719859744.jpg",
  },
  support: {
    mitLogo: "./support/mitLogo.png",
    brcLogo: "./support/brc.png",
    destinytionLogo: "./support/Destinytion.png",
    dewizeIoLogo: "./support/DewizeIo.png",
    redRabbitLogo: "./support/RedRabbit.png",
    renforcerLogo: "./support/Renforcer.png",
    rpEventsLogo: "./support/RpEvents.png",
    venagoLogo: "./support/Venago.png",
    vintageVisionLogo: "./support/VintageVision.png",
  },
 promoting: {
  make_in_india: './promoting/make_in_india.png',
  startup_india: './promoting/startup_india.png',
  skill_india: './promoting/skill_india.png',
  clean_india: './promoting/clean_india.png',
 },


  background: {
    RegistrationPage: "./background/registration-bg.png",
    DownloadPage: "./background/downloads.png",
    ebikeDesktop: './background/e-bike-comming-soon.jpeg',
    ebikeMobile: './background/e-bike-mobile.jpeg',
    errorDesktop: './background/404-desktop.jpeg',
    errorMobile: './background/404-mobile.jpeg',
    quadDesktop: './background/quad-bike-desktop.jpeg',
    quadMobile: './background/quadBike-mobile.jpeg',
    trainingDesktop: './background/training.jpeg',
    trainingMoile: './background/training-mobile.jpeg',
  },

  bannerImages: {
    img_1: "./banner/HFKC-Banner.png",
    img_2: "./banner/Iss5Banner.jpg",
    img_3: "./banner/groupPhoto.jpg",
    img_4: "./banner/closeUpShot.jpg",
    img_5: "./banner/closeUpShot2.jpg",
    img_6: "./banner/DarkCloseUpShot.jpg",
    img_7: "./banner/GroupCloseUp.jpg",
    img_8: "./banner/GroupCloseUp2.jpg",
    img_9: "./banner/groupPhoto.jpg",
    img_10: "./banner/highSaturationSingle.jpg",
    img_11: "./banner/KartAndCar.jpg",
    img_12: "./banner/KartAndCar2.jpg",
    img_13: "./banner/redBullGate.jpg",
  },
};
