export const assets = {
  global: {
    ick_logo: "./basics/Ick-logo.png",
    footerImg: "./basics/trackImg.jpg",
    hindustanMotorsportsLogo: "./basics/hindustan-motorsports.png",
    dotPattern: "/basics/dots-pattern.svg",
    hfkcLogo: "/basics/hfkc.png",
    commingSoon: '/basics/comming-soon.jpg'
  },
  heroSection: {
    backGroundVideo: "./hero/karting-video.mp4",
  },
  seasonSection: {
    tyre: "./season/tyre.png",
    person: "./season/aPerson.png",
    quadBiking: "./season/quad-bike-png.png",
    dirtBiking: "./season/dirt-bikingPng.jpg",
    hfkcLogo: "/season/hfkc.png",
    issSeason: "/season/ISS-series.png",
  },
  aboutSection: {
    smallKart: "./about/smallKart.png",
    NexusMotoSport: "./about/NexusMotoSport.jpg",
    IndianKarting: "./about/IndianKarting.jpg",
  },
  committeeSection: {
    Abhishek: "./committiee/AbhishekKaranjule.jpg",
    Aniket: "./committiee/AniketMind.jpg",
    Azmat: "./committiee/AzmatHussain.jpg",
  },
  socialIcons: {
    dribble: "./socialIcons/dribble.svg",
    linkedIn: "./socialIcons/linkedin.svg",
    facebook: "./socialIcons/facebook.svg",
  },
  gallery: {
    img_1: "./gallery/img_1.jpg",
    img_2: "./gallery/img_2.jpg",
    img_3: "./gallery/img_3.jpg",
    img_4: "./gallery/img_4.jpg",
    img_5: "./gallery/img_5.jpg",
    img_6: "./gallery/img_6.jpg",
    img_7: "./gallery/img_7.jpg",
    img_8: "./gallery/img_8.jpg",
    img_9: "./gallery/img_9.jpg",
  },
  support: {
    mitLogo: "./support/mitLogo.png",
    brcLogo: "./support/brc.png",
    destinytionLogo: "./support/Destinytion.png",
    dewizeIoLogo: "./support/DewizeIo.png",
    redRabbitLogo: "./support/RedRabbit.png",
    renforcerLogo: "./support/Renforcer.png",
    rpEventsLogo: "./support/RpEvents.png",
    venagoLogo: "./support/Venago.png",
    vintageVisionLogo: "./support/VintageVision.png",
  },
  background: {
    RegistrationPage: "./background/registration-bg.png",
    DownloadPage: "./background/downloads.png",
  },

  bannerImages: {
    img_1: "./banner/HFKC-Banner.png",
    img_2: "./banner/Iss5Banner.jpg",
    img_3: "./banner/groupPhoto.jpg",
    img_4: "./banner/closeUpShot.jpg",
    img_5: "./banner/closeUpShot2.jpg",
    img_6: "./banner/DarkCloseUpShot.jpg",
    img_7: "./banner/GroupCloseUp.jpg",
    img_8: "./banner/GroupCloseUp2.jpg",
    img_9: "./banner/groupPhoto.jpg",
    img_10: "./banner/highSaturationSingle.jpg",
    img_11: "./banner/KartAndCar.jpg",
    img_12: "./banner/KartAndCar2.jpg",
    img_13: "./banner/redBullGate.jpg",
  },
};
